### ISSUE TITLE
AFX block should extend HTML parser

### ISSUE THREAD

**Issue by jonnitto** [networkteam/vscode-neos-fusion#4]
The AFX block should extend the HTML parser. Like this, many autocompletion would work out of the box, for example https://github.com/bradlc/vscode-tailwindcss

**Comment by amtee** [comment]
Hey Jon, 

thank you for sharing your thoughts with us. 

Is it possible for you to create a PR? Let us know if not. 

Have a happy new year! 

ATB
Marcel

**Comment by jonnitto** [comment]
Unfortunately, I've no experience in creating plugins for VSCode.

**Comment by amtee** [comment]
Alright, no problem! 

I'll take this to the next discussion and give you a response ASAP.

**Comment by jonnitto** [comment]
Hi there!
Any progress in this?

**Comment by amtee** [comment]
Hey @jonnitto, 

I don't want to play the Rona card. It just did come to play yet. We'll keep you updated here.

**Comment by mhsdesign** [comment]
for now im just using:

{
    "emmet.includeLanguages": {
        "fusion": "html"
    }
}

but then its enabled globally in your fusion files.

**Comment by skurfuerst** [comment]
https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages
this could be tried :)

**Comment by skurfuerst** [comment]
see related PR :)
